[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
dmarket = { path = "../dmarket" }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.7"
env_logger = "0.11.6"
log = "0.4.26"
