[package]
name = "bitskins"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
common = { path = "../common" }
derive_more = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-cron-scheduler = { workspace = true }
tokio-tungstenite = { workspace = true }
thiserror = { workspace = true }
