[package]
name = "dmarket"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "2.1.1"
hex = "0.4.3"
rand = "0.8.5"
reqwest = { version = "0.12.7", features = ["json"] }
thiserror = "1.0.63"
url = "2.5.2"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
chrono = "0.4.38"
serde_qs = "0.13.0"
tokio = "1.40.0"
ringbuffer = "0.15.0"
sqlx = { version = "0.8.2", features = ["postgres"] }
log = "0.4.22"
