[package]
name = "dmarket"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
ed25519-dalek = "2.1.1"
hex = "0.4.3"
rand = "0.8.5"
reqwest = { version = "0.12.7", features = ["json"] }
thiserror = "1.0.63"
url = "2.5.2"
serde = "1.0.209"
serde_json = "1.0.127"
